spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saasdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: change-this-secret

logging:
  level:
    root: INFO
